ALTER TABLE users
ADD COLUMN IF NOT EXISTS "subscriptionStartDate" TEXT,
ADD COLUMN IF NOT EXISTS "subscriptionStart" TEXT,
ADD COLUMN IF NOT EXISTS "subscriptionEndDate" TEXT,
ADD COLUMN IF NOT EXISTS "subscriptionEnd" TEXT,
ADD COLUMN IF NOT EXISTS "subscriptionStatus" TEXT,
ADD COLUMN IF NOT EXISTS "membershipStatus" TEXT,
ADD COLUMN IF NOT EXISTS "renewedAt" TEXT,
ADD COLUMN IF NOT EXISTS "renewedBy" UUID,
ADD COLUMN IF NOT EXISTS "renewalRequested" BOOLEAN DEFAULT false;
