ALTER TABLE guest_invitations
ADD COLUMN IF NOT EXISTS invited_by UUID,
ADD COLUMN IF NOT EXISTS guest_name TEXT,
ADD COLUMN IF NOT EXISTS guest_phone TEXT,
ADD COLUMN IF NOT EXISTS guest_email TEXT,
ADD COLUMN IF NOT EXISTS meeting_date DATE,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending',
ADD COLUMN IF NOT EXISTS attendance_status TEXT,
ADD COLUMN IF NOT EXISTS attendance_updated_by UUID,
ADD COLUMN IF NOT EXISTS attendance_updated_by_name TEXT,
ADD COLUMN IF NOT EXISTS attendance_updated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS guest_whatsapp TEXT,
ADD COLUMN IF NOT EXISTS business_category TEXT,
ADD COLUMN IF NOT EXISTS meeting_id UUID,
ADD COLUMN IF NOT EXISTS meeting_title TEXT,
ADD COLUMN IF NOT EXISTS meeting_time TEXT,
ADD COLUMN IF NOT EXISTS venue TEXT,
ADD COLUMN IF NOT EXISTS invited_by_name TEXT,
ADD COLUMN IF NOT EXISTS invited_by_chapter TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS growth_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS workspace_checklist JSONB DEFAULT '{}'::jsonb;
